version: '3'
services:
  ruby_tutorial:
    restart: always
    build:
      context: .
      args:
        - UID=1000
        - GID=1000
        - UNAME=vagrant
    container_name: 'ruby_tutorial'
    working_dir: '/home/vagrant/opt'
    tty: true
    volumes:
      - ./workspace:/home/vagrant/opt
