version: '3'
services:
  ruby_tutorial:
    restart: always
    build:
      context: .
      args:
        - UID=70000
        - GID=70000
        - UNAME=vagrant1
    container_name: 'ruby_tutorial'
    working_dir: '/home/vagrant1/opt'
    tty: true
    volumes:
      - ./workspace:/home/vagrant1/opt
